In [ ]:
import torch 
x = torch.Tensor([
                  [[[0, 1], [2, 3]]],
                  [[[0, 0], [3, 4]]],
                  [[[0, 1], [3, 4]]]
                  ])
print(x.shape)
print(x)

torch.Size([3, 1, 2, 2])
tensor([[[[0., 1.],
          [2., 3.]]],


        [[[0., 0.],
          [3., 4.]]],


        [[[0., 1.],
          [3., 4.]]]])


In [ ]:
y = x.square().sum(dim = (1,2,3)).sqrt()
print(y.shape)
size = x.shape[1] * x.shape[2] * x.shape[3]
ones = torch.ones([x.shape[0], size])
z = y * torch.ones([x.shape[0], size]).t()
z.t().reshape(x.shape)


torch.Size([3])


tensor([[[[3.7417, 3.7417],
          [3.7417, 3.7417]]],


        [[[5.0000, 5.0000],
          [5.0000, 5.0000]]],


        [[[5.0990, 5.0990],
          [5.0990, 5.0990]]]])

In [ ]:
size = x.shape[1] * x.shape[2] * x.shape[3]
print(y * torch.ones(size))

RuntimeError: ignored

In [ ]:
x / y

RuntimeError: ignored

In [ ]:
import numpy as np
x = np.array([3, 1, 2])
np.argsort(x)[::-1][:2]


array([0, 2])

In [ ]:
np.argsort(x)[::-1][:2]

array([0, 2])

In [ ]:
import torch
x = torch.tensor([3, 1, 2])
torch.argsort(x, descending=True)[:2]

tensor([0, 2])

In [ ]:
import numpy as np
y = np.array([[3, 4, 4],
              [1, 2, 2],
              [5, 1, 1]])
y

prob = np.array([[3, 3, 4],
              [1, 2, 2],
              [5, 1, 1]])
prob

array([[3, 3, 4],
       [1, 2, 2],
       [5, 1, 1]])

In [ ]:
np.log(prob)

array([[1.09861229, 1.09861229, 1.38629436],
       [0.        , 0.69314718, 0.69314718],
       [1.60943791, 0.        , 0.        ]])

In [ ]:
y * np.log(prob)

array([[3.29583687, 4.39444915, 5.54517744],
       [0.        , 1.38629436, 1.38629436],
       [8.04718956, 0.        , 0.        ]])

In [ ]:
(y * np.log(prob)).sum()

24.055241749566612

In [ ]:
M = y.shape[1]
loss = 1 / M * (y * np.log(prob)).sum()
loss

8.018413916522203

In [ ]:
x = y
x

array([[3, 4, 4],
       [1, 2, 2],
       [5, 1, 1]])

In [ ]:
x - np.max(x)

array([[-2, -1, -1],
       [-4, -3, -3],
       [ 0, -4, -4]])

In [ ]:
axis = 2

In [ ]:
e = np.exp(x)
e

array([[ 20.08553692,  54.59815003,  54.59815003],
       [  2.71828183,   7.3890561 ,   7.3890561 ],
       [148.4131591 ,   2.71828183,   2.71828183]])

In [ ]:
e.sum()

300.62795377529125

In [ ]:
e.sum(axis = axis)

AxisError: ignored

In [ ]:
e / e.sum()

array([[0.06681194, 0.18161368, 0.18161368],
       [0.00904201, 0.02457874, 0.02457874],
       [0.49367718, 0.00904201, 0.00904201]])

In [ ]:
e / e.sum(axis = axis)

array([[0.11731043, 0.84379473, 0.84379473],
       [0.01587624, 0.1141952 , 0.1141952 ],
       [0.86681333, 0.04201007, 0.04201007]])

In [ ]:
N = 21
x = np.array([1, 0, 10, 20])
b = np.zeros((N, x.shape[0]))
print(x)
print(b)
b[x, np.arange(x.size)] = 1
print(b)




[ 1  0 10 20]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
from google.colab import drive 
drive.mount("/content/drive")
%cd "drive/My Drive/Colab Notebooks/MLGS/project3"
%pwd

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks/MLGS/project3


'/content/drive/My Drive/Colab Notebooks/MLGS/project3'

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
from scipy import spatial
%matplotlib inline

In [ ]:
data = np.load("task03_data.npy", allow_pickle=True)
reviews_1star = [[x.lower() for x in s] for s in data.item()["reviews_1star"]]
reviews_5star = [[x.lower() for x in s] for s in data.item()["reviews_5star"]]



In [ ]:
reviews_1star[0:2]

[['in',
  'honor',
  'of',
  'an',
  'upcoming',
  'trip',
  'to',
  'vegas',
  'i',
  'thought',
  "i'd",
  'review',
  'some',
  'of',
  'my',
  'most',
  'and',
  'least',
  'favorite',
  'places',
  'in',
  'the',
  'town'],
 ['this',
  'place',
  'tops',
  'the',
  'least',
  'favorite',
  'list',
  'by',
  'a',
  'long',
  'shot']]

In [ ]:
reviews_5star[0:2]

[['the',
  'surf',
  'and',
  'turf',
  'here',
  'was',
  'one',
  'of',
  'the',
  'best',
  "i've",
  'had'],
 ['filet', 'mignon', 'and', 'lobster', 'tail', 'was', 'very', 'good']]

In [ ]:
reviews_1star = [['b', 'is', 'for', 'boy'], ['a', 'is', 'for', 'apple']]
reviews_5star = [['z', 'is', 'for', 'zoo'], ['y', 'is', 'for', 'yellow']]

In [ ]:
vocabulary = [x for s in reviews_1star + reviews_5star for x in s]
vocabulary

['b',
 'is',
 'for',
 'boy',
 'a',
 'is',
 'for',
 'apple',
 'z',
 'is',
 'for',
 'zoo',
 'y',
 'is',
 'for',
 'yellow']

In [ ]:
for s in reviews_1star + reviews_5star:
  for x in s:
    print(x)

b
is
for
boy
a
is
for
apple
z
is
for
zoo
y
is
for
yellow


In [ ]:
embedding

In [10]:
import numpy as np

x = np.array([1,1,1,1,1,1,1,1]).reshape(2,4)

f = 'x.npy'
np.save(f, x)
np.load(f)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])