In [0]:
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions.multivariate_normal import MultivariateNormal
from sklearn.datasets import make_moons

In [0]:
base_dist = MultivariateNormal(torch.zeros(2), torch.eye(2))

In [0]:
z = base_dist.sample()
print(z)

tensor([ 0.0665, -0.1686])


In [0]:
batch_size = 10
# x = torch.Tensor(batch_size, 2)
# for i in range(batch_size):
#   x.add(base_dist.sample())
# x = x * 10000000000
x = torch.Tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
print(x)
x.shape

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


torch.Size([3, 2])

In [0]:
log_scale = nn.Parameter(torch.Tensor([1, 2]))
print(log_scale)

Parameter containing:
tensor([1., 2.], requires_grad=True)


In [0]:
shift = nn.Parameter(torch.Tensor([2, 3]))
print(shift)

Parameter containing:
tensor([2., 3.], requires_grad=True)


In [0]:
# y = torch.mm(x, x.t())
# 

y = log_scale * x[:, :] + shift
print(y)



tensor([[ 3.,  7.],
        [ 5., 11.],
        [ 7., 15.]], grad_fn=<AddBackward0>)


In [0]:
y = x * log_scale + shift
print(y)

tensor([[ 3.,  7.],
        [ 5., 11.],
        [ 7., 15.]], grad_fn=<AddBackward0>)


In [0]:
y = log_scale * x  + shift
print(y)

tensor([[ 3.,  7.],
        [ 5., 11.],
        [ 7., 15.]], grad_fn=<AddBackward0>)


In [0]:
x = (y - shift) / log_scale
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], grad_fn=<DivBackward0>)


In [0]:
from sklearn.datasets import make_moons
dataset_1 = CircleGaussiansDataset(n_gaussians=1, n_samples=500)

NameError: ignored

In [0]:
x tensor([[-1.7924,  1.4232],
        [-0.1067,  0.4870],
        [-1.6837,  0.3379],
        [ 0.3275,  0.1729],
        [ 1.3409, -0.4855],
        [ 1.2897,  2.3060],
        [-0.0732,  0.2745],
        [ 2.1805,  0.0215],

scale tensor([1., 1.], device='cuda:0', grad_fn=<ExpBackward>)
shift tensor([1., 1.], device='cuda:0', grad_fn=<ExpBackward>)
with torch - y, log_det_jac: tensor([[-1.7924,  1.4232],
        [-0.1067,  0.4870],
        [-1.6837,  0.3379],
        [ 0.3275,  0.1729],
        [ 1.3409, -0.4855],
        [ 1.2897,  2.3060],
        [-0.0732,  0.2745],
        [ 2.1805,  0.0215],

tensor(2., device='cuda:0', grad_fn=<SumBackward0>

IndexError: ignored

In [0]:
z_prime = torch.ones(10, 2) * 0.5
z_prime = torch.bernoulli(z_prime)